export const ActivityType = {
  RUNNING: 'RUNNING',
  WALKING: 'WALKING',
  SWIMMING: 'SWIMMING',
  BOXING: 'BOXING',
  PILATES: 'PILATES',
  STRENGTH_TRAINING: 'STRENGTH_TRAINING',
  SLEEPING: 'SLEEPING',
  JUMPING: 'JUMPING',
  MARTIAL_ARTS: 'MARTIAL_ARTS',
  AEROBICS: 'AEROBICS',
  CRICKET: 'CRICKET',
  FOOTBALL: 'FOOTBALL',
  TENNIS: 'TENNIS',
  HOCKEY: 'HOCKEY',
  BATMINTON: 'BATMINTON',
  CYCLING: 'CYCLING',
  OUTDOOR_CYCLING: 'OUTDOOR_CYCLING',
  YOGA: 'YOGA',
  HIIT: 'HIIT',
  CARDIO_TRAINING: 'CARDIO_TRAINING',
};

export const ActivityTypeLabels = {
  RUNNING: 'Running',
  WALKING: 'Walking',
  SWIMMING: 'Swimming',
  BOXING: 'Boxing',
  PILATES: 'Pilates',
  STRENGTH_TRAINING: 'Strength Training',
  SLEEPING: 'Sleeping',
  JUMPING: 'Jumping',
  MARTIAL_ARTS: 'Martial Arts',
  AEROBICS: 'Aerobics',
  CRICKET: 'Cricket',
  FOOTBALL: 'Football',
  TENNIS: 'Tennis',
  HOCKEY: 'Hockey',
  BATMINTON: 'Badminton',
  CYCLING: 'Cycling',
  OUTDOOR_CYCLING: 'Outdoor Cycling',
  YOGA: 'Yoga',
  HIIT: 'HIIT',
  CARDIO_TRAINING: 'Cardio Training',
};

export const ActivityTypeArray = Object.values(ActivityType);
